{% set version = "0.2.7" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-shinytree
  version: {{ version|replace("-", "_") }}

source:
  fn: shinyTree_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/shinyTree_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/shinyTree/shinyTree_{{ version }}.tar.gz
  sha256: 4387f11f47fd24f260b53224a884101156964944d68dee8583674f761513dd49

build:
  noarch: generic
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: testthat
requirements:
  host:
    - r-base
    - r-htmlwidgets
    - r-jsonlite
    - r-promises
    - r-shiny >=0.9.0
    - r-stringr
  run:
    - r-base
    - r-htmlwidgets
    - r-jsonlite
    - r-promises
    - r-shiny >=0.9.0
    - r-stringr

test:
  commands:
    - $R -e "library('shinyTree')"           # [not win]
    - "\"%R%\" -e \"library('shinyTree')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=shinyTree
  license: MIT
  summary: Exposes bindings to jsTree -- a JavaScript library that supports interactive trees -- to enable a rich, editable trees in Shiny.
  license_family: MIT

  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE
extra:
  recipe-maintainers:
    - conda-forge/r
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr
