# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_r_base3.4.1target_platformosx-64
    - CONFIG=osx_r_base3.5.1target_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "SETgsLFb8d7teQ09u+woOSXD6Ti+5akxh9Q5Lqs5+hAA+JkgZEsbmizaAqQ64nisz4dGeBxoq2owCzyasbhl47KaTenUIcuhjKE+9o/VQRCRxIHPea0Ujb6ZwFUdAqJ7+i1XI1h/pKvNsAm5R4bSCvwh3Lg8wcarTZjoAmH1hDY+Y3pp6D45vuBB904WhSuvXBcuJPqO9SvqTa28KlbvZmGF1vZs2YN5aPrJtTG7qSF7hpjgbzMTLBgGCC6SxAphNyiMZBLSI8FVB8gxKOVMGJnls4K61+HeiMzh8fZHfOOR+Gak7+5DbupzNqlUS1QuqdzOzYZyqG3uYLffEJ/NnqpiV9eoO3UlV5uAbYRPCoXKw/8snDTnyU8EsjLpXdNX8UzGSs3M0HD+WEd0FZcyGK20/wlF7rhlAfiTwnsUFnVnRbdywpiolWRlqaJ4yqMxrPQMfrY+maL24nzCQnQZkmmiDW7RYjze2cOOMrGsH9qZ9Edh3f46nMZZyIwAvYTQlO6PT84CJU5DsgoPgFCZQ6krd299vMbuoDI0p6CS8Kj4hpS2+5rm7rzFElzl/GXDwTxjIh/+Td2qvppuQI4VdxuU4Zu8v3ZYPPs79J5yV5OcXv70znzc78sy9hWU27vK6ZGyfMsnOKK9geP69x0+tBMl/HfLd/A3jNhKb/fG+rg="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
