appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: SETgsLFb8d7teQ09u+woOSXD6Ti+5akxh9Q5Lqs5+hAA+JkgZEsbmizaAqQ64nisz4dGeBxoq2owCzyasbhl47KaTenUIcuhjKE+9o/VQRCRxIHPea0Ujb6ZwFUdAqJ7+i1XI1h/pKvNsAm5R4bSCvwh3Lg8wcarTZjoAmH1hDY+Y3pp6D45vuBB904WhSuvXBcuJPqO9SvqTa28KlbvZmGF1vZs2YN5aPrJtTG7qSF7hpjgbzMTLBgGCC6SxAphNyiMZBLSI8FVB8gxKOVMGJnls4K61+HeiMzh8fZHfOOR+Gak7+5DbupzNqlUS1QuqdzOzYZyqG3uYLffEJ/NnqpiV9eoO3UlV5uAbYRPCoXKw/8snDTnyU8EsjLpXdNX8UzGSs3M0HD+WEd0FZcyGK20/wlF7rhlAfiTwnsUFnVnRbdywpiolWRlqaJ4yqMxrPQMfrY+maL24nzCQnQZkmmiDW7RYjze2cOOMrGsH9qZ9Edh3f46nMZZyIwAvYTQlO6PT84CJU5DsgoPgFCZQ6krd299vMbuoDI0p6CS8Kj4hpS2+5rm7rzFElzl/GXDwTxjIh/+Td2qvppuQI4VdxuU4Zu8v3ZYPPs79J5yV5OcXv70znzc78sy9hWU27vK6ZGyfMsnOKK9geP69x0+tBMl/HfLd/A3jNhKb/fG+rg=}
bot:
  automerge: true
